### ISSUE TITLE
Can you please add a bulk action to add to a template category inside elementor's "my templates" section?

### ISSUE THREAD

**Issue by jazir555** [deckerweb/builder-template-categories#1]
Having to manually add individual templates to categories kind of defeats the purpose of this plugin

**Comment by deckerweb** [comment]
@jazir5 Thanks for your feedback!
This is already possible using the default bulk actions of WordPress itself - which are available for any post type and taxonomy. It works the same way like adding categories to posts in bulk.

I also made a little video about it so you can see what I mean - with "Elementor My Templates" as an example:
https://www.youtube.com/watch?v=KyCY-cGAB9o

**Comment by jazir555** [comment]
@deckerweb 

Would it be possible to add a new bulk action "add to category" to clarify it for myself and other users? I feel that would be more intuitive than edit. I did not know edit allowed that, which is why i was confused, thank you for the video.

**Comment by deckerweb** [comment]
I totally understand where you're coming from and it seems not that obvious, you are right. WordPress itself should be more open on what is possible, I guess :-)

To replicate the functionality itself (from WordPress Core) seems unpossible to me and/or not useful.
However, what I can - and will - do, is this: manipulate the "Edit" string into something like "Edit, add Category etc.". Also, I will add explanation to plugins readme file on .org (the plugin page) and on the help tab on the integrated post types (help tab will come with next version v1.1.0 which is pretty much ready...!).

**Comment by jazir555** [comment]
@deckerweb 

Thank you so much for being so responsive and adding that QOL change for me. I appreciate it.

https://wordpress.org/plugins/media-library-plus/

Would it be possible to eventually implement an interface like wordpress media library folders into the plugin? That would be a very intuitive and conveinient way to manage templates.

**Comment by deckerweb** [comment]
No, such features are not planned in any way.
The plugin as it is and my vision for it was and is: being really simple, leightweight and focused - on only one task: make it easier to organize templates for admins/ site builders. Working with the resources WordPress offers by default. That way the footprint of the plugin can be kept very very small, almost "unvisible".

If it were for managing "real" stuff like media files (like in the mentioned other plugin above) than it would make sense to maybe add more stuff.

Also, for the current integrations - 28 third-party integrations as of v1.1.0 - this would add A LOT of bloat to the plugin that I don't want.
