### ISSUE TITLE
Would it be possible to add all pages categorized as "pages" to the pages section in the admin panel?

### ISSUE THREAD

**Issue by jazir555** [deckerweb/builder-template-categories#3]
When pages are created in the Elementor templates section, they are not added to pages in the sidebar of the admin panel. When pages are created within the pages section, they are not editable via elementor until you click edit on the page, then edit with elementor. This is very frustrating and requires me to create pages in the pages section for plugins that only read pages from within that section of the admin panel. The simplest solution i can think of would be to autoappend all templates assigned to the pages category via this plugin to the pages section of the admin panel.

I would be very grateful if you could add this functionality. I'm running into this issue with woocommerce, it will not allow me to assign pages to the cart, checkout, account or terms and conditions pages created within the elementor my templates section. Which means i have to go through the convoluted process of creating it in pages, clicking edit, then clicking edit with elementor, in order to customize these pages via elementor.

**Comment by jazir555** [comment]
Guh, sorry, pressing enter immediately posts it, accidental. Couldn't get the description written first

**Comment by deckerweb** [comment]
From how I understand you, I guess there is some confusing or misunderstanding on what "Pages" in Elementor Templates are: these are NOT pages like default WordPress pages, therefore they cannot appear there. Also technically it is not possible to bind various registered post types to ONE admin menu/submenu or even ONE post list table.

Elementor has various so-called "document types" - these refer to different types of Elementor template elements. Currently there are: Pages, Sections, Widgets, Single, Archive etc.

Document type "Pages" means a complete HTML document with the needed meta info in the header especially. But since the Elementor Template post type is registered without an archive it cannot be displayed standalone but its content only within a real WordPress page or a real public, archive-based Post Type in WP.

Verdict: It is just not possible technically and it would beyond the scope and focus of this plugin.

**Comment by jazir555** [comment]
I am not understanding, perhaps you can clarify. If I make a page within the pages section, then click edit, then click edit with elementor, I can design a page via elementor in the exact same fashion as if I had made a page template within the my templates section of elementor.

In elementor, it would have the category "page", which from your explanation as I understand it, while it may also be called "page" it is coded to be recognized as a different type of file and therefore cannot shown in the "pages" section of the admin dashboard.

My point is to say, if I go through the convoluted process of creating a page in "pages", clicking edit under the page in the pages section, and then  clicking the blue edit with elementor button.

As it appears to me, once I have chosen to edit the page with elementor after clicking the blue edit button within the pages "edit" section, the page is functionally identical to a page created in the "my templates" section of elementor, aside from it's categorization. 

The pages are fully editable with elementor and I cannot discern a difference, aside from the extended irritating process of actually creating an editable elementor page within the "pages" section.

As I mentioned, many plugins, woocommerce for example, will only read pages created within the "pages" section in the admin dashboard. I can create the page via the process mentioned, edit it with elementor and then link it to woocommerce via the drop-down. This method does work, but is incredibly irritating and time consuming.

Are you saying that there is no way to get elementor templates categorized as pages to display in the pages section? Why would that be undoable if elementor is capable of editing pages within that section?

**Comment by deckerweb** [comment]
> Are you saying that there is no way to get elementor templates categorized as pages to display in the pages section? Why would that be undoable if elementor is capable of editing pages within that section?

This is just technically not possible.
These are 2 different post types:
WordPress pages --> registered post type: "page"
Elementor Templates --> registered post type: "elementor_library"
--> these both CANNOT be listed together in an overview table (post list table) in the admin.

I guess what is confusing you is the labeling as "page"?!?
But please see the difference as well here: the document type "Page" for Elementor templates has nothing to do with the WordPress type "Page". The Elementor document type is a special thing which introduced Elementor for their builder to be capable of doing theme templates and other stuff.

Technically the some of the basic attributes of both post types (page, elementor_library) are the same: title, content area etc. ---> therefore both can be edited with the Elementor Builder.

WooCommerce for itself is programmed to only recognize pages from WordPress ("page"). Maybe it could be tweaked to make it aware of the "elementor_library" post type. But that would require to change some arguments of this post type that would lead to other (non-wanted) consequences. So it makes no sense.

The Elementor template post type and its "sub type" for documents labeled as "Pages", "Section" etc. serves a specific purpose within the Elementor context.

The document type "Page" from Elementor Templates is needed for example for the Maintenance Templates and Coming Soon Templates in Elementor. And also other Elementor Add-Ons do stuff with this template post type, and especially with the "sub type" (document type) "Page" in Elementor.

The only thing you can do, is mapping the document type "Page" from Elementor Templates to a submenu to WordPress Pages. This would lead to something like "Elementor Pages" as a submenu label under "Pages" in WP. When clicking on it, then it will work as a quick jump link to the document type "Page" in Elementor Templates. So it is just easier and might save some time. --> If you are interested I can give you a code snippet to make it work (really easy!).
(Also, if you want to add my categories (from my plugin Builder Template Categories) also to regular WordPress pages, that is possible as well - also with a simple snippet I will give of course.)

The questions that I have for you are these:
- What do you want to achieve in the end?
- Maybe you can give your exact use case what to do - maybe there are other alternatives to make that easier for you with some (other) plugins, code snippets whatever. Just freel free to give as many details as possible.
- When other plugins like WooCommerce need the connection to regular WordPress pages then just use these one and just edit them with Elementor - would that be an option for you?
- When Elementor or specific Elementor Add-Ons require Elementor Templates then use this template post type ---> that's the way I do that for over a year now and working great so far.

You can also write to Elementor support maybe they can explain it way better than I could do... :-)

**Comment by deckerweb** [comment]
Also, see the different "document types" (Pages, Section etc.) in Elementor post type ("elementor_library") just as another taxonomy to sort/differentiate those stuff for different purposes (which Elementor does under the hood).

**Comment by deckerweb** [comment]
...another thing to consider:
Elementor recently changed the tab label from "Page" to "Content"
but in the overview table below it is still listed as "Pages" (should then be "Content" now also...)

So both labels mean and point to the same thing! But I fully understand it even confuses more. I will make a ticket for Elementor so they hopefully change that and make it more clear.

In my opinion changing the labelling to "Content" makes a bit more sense so users don't confuse with regular WP pages... :-)

**Comment by deckerweb** [comment]
Here are the promised code snippets:

1) Quick jump link to map Elementor document type page to WP Pages:
https://gist.github.com/deckerweb/a39987319fb7a2f51126a26c7a6ee662

2) Register Template Categories for regular WP Pages (via BTC Plugin):
https://gist.github.com/deckerweb/dd00884e81783e7d21046ae0a72ed683

Note: These snippets are working - just tested myself. Recommended usage is via the awesome and free "Code Snippets" plugin: https://wordpress.org/plugins/code-snippets/ (it is enough to let both snippets execute in admin area then)

**Comment by jazir555** [comment]
First i just want to say you are awesome, thank you so much for taking the time to answer my questions and not only that, add functionality and provide incredibly helpful solutions. Thank you!

•	What do you want to achieve in the end?

Woocommerce is the example that currently comes to mind, but I have run into this issue with some other plugins before, the names of which escape me at the moment. What I want to achieve is to allow any other plugin which requires a page to be created or be shown in the “pages” section to have access to and select elementor pages. In the case of woocommerce I think it’s just it’s way of linking to the page, which is how I imagine other plugins work. Any plugin which requires classification in the pages section to modify or interact with a page. 

I want to create all pages I need for any site within elementor, therefore having to switch back and forth for specific use cases as well as necessitating the time consuming process to do so is the frustration. It would be less time consuming and simpler were other plugins capable of locating and interacting with elementor pages, without going through the tedious process of creating them within the pages section to be edited with elementor as I described. 

•	When other plugins like WooCommerce need the connection to regular WordPress pages then just use these one and just edit them with Elementor - would that be an option for you?

I suppose, but as mentioned above, this comes up from time to time in multiple situations, and it would be easier if they just displayed in both places, my templates and pages. I want to be able to hand off my sites to my clients at some point, so that they can manage the content themselves. It is confusing for nontechnical users(as well as myself) who may not understand why pages they have created do not display in the clearly labeled “pages” tab on the sidebar, understandably. It will help reduce client frustration and simplify explaining the tools to friends who want to learn the editor.

•	Maybe you can give your exact use case what to do - maybe there are other alternatives to make that easier for you with some (other) plugins, code snippets whatever. Just freel free to give as many details as possible.

Having all content pages created in elementor display in the “pages” section so they are detectable and interactable with other plugins, as well as for user clarity. Intuitively I would think pages created via elementor would be displayed in the section labeled “pages”. Elementor unfortunately makes no clear distinction that they will not, nor why that is the case. 

So when I run into plugins that require pages specifically made in the pages section, if I have already created it inside the elementor my templates section and did not realize that the plugin I need to interact with the page requires it to be created within the “pages” section, I then need to annoyingly completely recreate the page within the pages section, so that the plugin in question can actually see and manipulate the page! As you can understand from this example, it could mean hours of time flushed down the drain as the page will not be fully functional unless it can be read by whatever the external plugin is. 

The solution to me seems to be allowing any plugin to see elementor templates classified as pages to be displayed in the “pages” section in the admin sidebar, so they can interact with them and link to them. This also solves the issue of confusion of where the pages are located for the user, by displaying them in the section they would intuitively assume a page template would be displayed.

**Comment by jazir555** [comment]
![pages section](https://user-images.githubusercontent.com/31750063/46339946-f3502300-c5e8-11e8-9c73-b18bf8ebbc4e.PNG)

this is the pages section i am referring to

**Comment by jazir555** [comment]
I won't have time to test your code snippets until tomorrow, but thank you so so much for taking the time to write them.

**Comment by jazir555** [comment]
Hi David, i tested the first code snippet and am unsure how to make it work, as it does not appear to. I assume i imported it wrong. I have taken screenshots, hopefully this helps you troubleshoot. Thank you again for taking the time to respond

![current pages page cannot see code snippet effect](https://user-images.githubusercontent.com/31750063/46440582-b08d6880-c718-11e8-8d01-bcca42b3e3db.PNG)
![code snippet for page categories](https://user-images.githubusercontent.com/31750063/46440583-b125ff00-c718-11e8-8983-0c7e726449c4.PNG)

**Comment by jazir555** [comment]
I notice code snippets has the ability to import xml and json files, is it easier to convert it one of them and import it? Or am i just formatting it wrong, i just copy pasted the text of the code you posted via ctrl+c and then ctrl+v to paste.

**Comment by jazir555** [comment]
Also, could you please link me to the btc plugin, code snippets throws an error trying to activate the second snippet as i do not have the plugin. Searching btc plugins brings me cryptocurrency plugins results in google as that is the most common acronym for bitcoin.

**Comment by deckerweb** [comment]
I thought you were already using my plugin since you opened an issue here on the development repo.
The plugin's name is "Builder Template Categories" ---> in the WordPress plugin installer in your WP Admin search for "builder template categories" then it will appear for install. (I just call it short "BTC" :-) )

For the "Code Snippets" plugin:
The import feature for this plugin is only useful if you have an export file made by that plugin.
To use my snippets linked above, just copy + paste the code, but without the opening php line!!!
Also give a title for better organizing internally.

Yes, the second snippet depends on my plugin "Builder Template Categories" please install it first!

**Comment by jazir555** [comment]
I actually have had builder template categories installed since before i opened the first issue thread. The second code snippet activated successfully after reposting in the code snippet, odd. Perhaps i had an extra space or something somewhere.

However, i had deactivated the first code snippet before activating the second and reactivated the first after activating the second successfully. The first one had activated correctly prior. i now receive this error on every page trying to load the admin dashboard

![code snippets error](https://user-images.githubusercontent.com/31750063/46441644-fdbf0980-c71b-11e8-8281-efbe1bae11d3.PNG)

**Comment by jazir555** [comment]
I know i can fix this by disabling/deleting the code snippets plugin, i'm not sure what i did wrong however.

**Comment by deckerweb** [comment]
You can use their "panic constant" and add it to your wp-config to temporarily deactivate the snippets:
`define('CODE_SNIPPETS_SAFE_MODE', true);`
See their FAQ: https://wordpress.org/plugins/code-snippets/#faq

I assume you had my second snippet added twice.
Just delete those snippets and try again.

You don't need the "Code Snippets" plugin (I find it convenient, though), you can add snippets to your functions.php or a functionality plugin as well.

**Comment by jazir555** [comment]
Cool, i added the safe mode tag to the wp-config file, deleted the plugins, readded and activated them. However, pages tab seems to remain unchanged.
![pages with snippets active unchanged](https://user-images.githubusercontent.com/31750063/46442237-c3566c00-c71d-11e8-8e59-851b0fbe3565.PNG)
![snippet 2 activated](https://user-images.githubusercontent.com/31750063/46442239-c7828980-c71d-11e8-8f78-904c83ea3550.PNG)
![snippet 1 activated](https://user-images.githubusercontent.com/31750063/46442240-c7828980-c71d-11e8-8b0a-67d0add89bf4.PNG)

**Comment by jazir555** [comment]
Both snippets appear to be activated within the code snippets admin panel

**Comment by deckerweb** [comment]
The "Page" tab under Elementor My Templates will not change with these snippets!

I see at least second snippet is working as your regular WP pages now also use additional template categories :-)

Look at left-hand admin menu - each snippets adds one link:
![snippets-btc](https://user-images.githubusercontent.com/870135/46442509-266df000-c76a-11e8-93fd-8824f7bb2747.png)

**Comment by jazir555** [comment]
Ah i see, this will make locating pages simpler for clients and myself, thank you. This does not allow me to solve the issue i have with plugins such as woocommerce however.
![woocommerce page selection](https://user-images.githubusercontent.com/31750063/46443181-3b726100-c721-11e8-82c2-ebafcf2dcd9b.PNG)

I am still unable to direct woocommerce to select a page within the template library. Although that may not be what your snippets do as a function from what i assume, does this simply allow you to access these pages via these two links on the sidebar, sort of like a hotlink to the section, just within the pages submenu on the sidebar as opposed to within the elementor "my templates" section? 

This function is certainly useful for both clarity and speed, but does not solve the issue of being able to select elementor pages from plugins like woocommerce or others which will only see links to pages within the pages section.

This remaining issue is probably my most annoying remaining issue with categorization. If i build a page within the elementor my templates section, only to realize after the fact that a plugin necessitates the page exists within the "pages" section on the admin panel, the page created in the elementor my templates section is essentially worthless as they are incapable of being read by and integrating with  the plugin. Just a ton of time down the drain. Solving this would be a huge boon to me.

Again, thank you so, so, so much for taking the time to help me solve these issues. I truly appreciate it.

**Comment by jazir555** [comment]
Is it possible to use something like this plugin to achieve what i want?

https://adminmenueditor.com/

**Comment by jazir555** [comment]
Actually this plugin appears more suitable: https://toolset.com/documentation/post-relationships/how-to-set-up-post-relationships-using-toolset/?utm_source=typesplugin&utm_campaign=types&utm_medium=postedit&utm_term=parent_child_relationship?utm_source=typesplugin&utm_campaign=types&utm_medium=postedit&utm_term=parent_child_relationship

I am unsure how to apply the settings. Do either of these make this functionality possible or am i wasting my time?
